"""Initial schema

Revision ID: 7b673c806e73
Revises: 
Create Date: 2026-07-11 05:17:37.325363

"""
from alembic import op
import sqlalchemy as sa
import app.sqltypes  # noqa: F401  (lets migrations resolve custom column types)


# revision identifiers, used by Alembic.
revision = '7b673c806e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distance_matrix_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_type', sa.String(length=10), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('dest_type', sa.String(length=10), nullable=False),
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distance_matrix_entries')),
    sa.UniqueConstraint('origin_type', 'origin_id', 'dest_type', 'dest_id', name='uq_distance_matrix_entries_pair')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plant_closed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('loading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('shift_start_earliest', app.sqltypes.TimeType(length=8), nullable=False),
    sa.Column('max_shift_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('service_time_solo_minutes', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('has_dock', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('open_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('close_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('fixed_appointment_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('volume_units', sa.Integer(), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_stops_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stops'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('assigned_ssr_id', sa.Integer(), nullable=True),
    sa.Column('truck_capacity_volume', sa.Integer(), nullable=False),
    sa.Column('truck_capacity_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_ssr_id'], ['users.id'], name=op.f('fk_routes_assigned_ssr_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_routes_plant_id_plants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_table('stop_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('holiday_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holiday_id'], ['holidays.id'], name=op.f('fk_stop_closures_holiday_id_holidays'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_stop_closures_stop_id_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop_closures'))
    )
    op.create_table('stop_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_stop_contacts_stop_id_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop_contacts'))
    )
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('recommended_departure_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('estimated_return_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('assistants_required', sa.Integer(), nullable=True),
    sa.Column('total_distance_meters', sa.Float(), nullable=True),
    sa.Column('total_drive_seconds', sa.Float(), nullable=True),
    sa.Column('total_service_seconds', sa.Float(), nullable=True),
    sa.Column('capacity_utilization_pct', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('feasible', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_optimization_results_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_results'))
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('service_days', sa.String(length=20), nullable=True),
    sa.Column('volume_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_route_stops_stop_id_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'stop_id', name='uq_route_stops_route_stop')
    )
    op.create_table('optimization_result_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_result_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('estimated_departure_time', app.sqltypes.TimeType(length=8), nullable=True),
    sa.Column('cumulative_volume', sa.Integer(), nullable=True),
    sa.Column('time_window_ok', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_result_id'], ['optimization_results.id'], name=op.f('fk_optimization_result_stops_optimization_result_id_optimization_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_optimization_result_stops_stop_id_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_result_stops'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_result_stops')
    op.drop_table('route_stops')
    op.drop_table('optimization_results')
    op.drop_table('stop_contacts')
    op.drop_table('stop_closures')
    op.drop_table('routes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('roles')
    op.drop_table('plants')
    op.drop_table('holidays')
    op.drop_table('distance_matrix_entries')
    # ### end Alembic commands ###
