"""Add identity_sub to users

Revision ID: c5f4973e017a
Revises: 7b673c806e73
Create Date: 2026-10-01 20:49:07.384309

"""
from alembic import op
import sqlalchemy as sa
import app.sqltypes  # noqa: F401  (lets migrations resolve custom column types)


# revision identifiers, used by Alembic.
revision = 'c5f4973e017a'
down_revision = '7b673c806e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_sub', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_identity_sub'), ['identity_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_identity_sub'))
        batch_op.drop_column('identity_sub')

    # ### end Alembic commands ###
